apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npminstall
spec:
  workspaces:
    - name: source
  steps:
    - name: install
      image: node:20
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        npm install

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tests
spec:
  workspaces:
    - name: source
  steps:
    - name: jasmine
      image: node:20
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        npx jasmine